"""
Agno 内置工具目录 (v2)。

TOOLKIT_CATALOG: type_key → {module_path, class_name, name, category, description}
供 GenericToolkitBuilder 按 type 动态加载对应 Agno 工具类。
"""

TOOLKIT_CATALOG: dict[str, dict] = {
    # ── 搜索与网页 ────────────────────────────────────────────────────────────
    "duckduckgo":   {"module_path": "agno.tools.duckduckgo", "class_name": "DuckDuckGoTools", "name": "DuckDuckGo 搜索", "category": "搜索", "description": "免费 DuckDuckGo 网络搜索"},
    "tavily":       {"module_path": "agno.tools.tavily", "class_name": "TavilyTools", "name": "Tavily 搜索", "category": "搜索", "description": "Tavily AI 搜索（需 API Key）"},
    "serper":       {"module_path": "agno.tools.serper", "class_name": "SerperTools", "name": "Serper 搜索", "category": "搜索", "description": "Google 搜索 via Serper（需 API Key）"},
    "serpapi":      {"module_path": "agno.tools.serpapi", "class_name": "SerpApiTools", "name": "SerpAPI 搜索", "category": "搜索", "description": "SerpAPI Google/Bing 搜索"},
    "brave_search": {"module_path": "agno.tools.bravesearch", "class_name": "BraveSearchTools", "name": "Brave 搜索", "category": "搜索", "description": "Brave 隐私搜索引擎"},
    "baidu_search": {"module_path": "agno.tools.baidusearch", "class_name": "BaiduSearchTools", "name": "百度搜索", "category": "搜索", "description": "百度搜索"},
    "exa":          {"module_path": "agno.tools.exa", "class_name": "ExaTools", "name": "Exa 搜索", "category": "搜索", "description": "Exa 语义搜索"},
    "searxng":      {"module_path": "agno.tools.searxng", "class_name": "Searxng", "name": "Searxng", "category": "搜索", "description": "自托管 Searxng 元搜索"},
    "perplexity":   {"module_path": "agno.tools.perplexity", "class_name": "PerplexitySearch", "name": "Perplexity 搜索", "category": "搜索", "description": "Perplexity AI 搜索"},
    "website":      {"module_path": "agno.tools.website", "class_name": "WebsiteTools", "name": "网站工具", "category": "搜索", "description": "抓取并读取网站内容"},
    "webbrowser":   {"module_path": "agno.tools.webbrowser", "class_name": "WebBrowserTools", "name": "网页浏览器", "category": "搜索", "description": "打开网页链接"},
    "trafilatura":  {"module_path": "agno.tools.trafilatura", "class_name": "TrafilaturaTools", "name": "Trafilatura 抓取", "category": "搜索", "description": "网页正文提取"},
    "jina":         {"module_path": "agno.tools.jina", "class_name": "JinaReaderTools", "name": "Jina Reader", "category": "搜索", "description": "Jina Reader 网页转 Markdown"},
    "spider":       {"module_path": "agno.tools.spider", "class_name": "SpiderTools", "name": "Spider 爬虫", "category": "搜索", "description": "Spider.cloud 网页爬取"},
    "crawl4ai":     {"module_path": "agno.tools.crawl4ai", "class_name": "Crawl4aiTools", "name": "Crawl4AI", "category": "搜索", "description": "Crawl4AI 异步网页爬取"},
    "firecrawl":    {"module_path": "agno.tools.firecrawl", "class_name": "FirecrawlTools", "name": "Firecrawl", "category": "搜索", "description": "Firecrawl 结构化网页抓取"},
    "scrapegraph":  {"module_path": "agno.tools.scrapegraph", "class_name": "ScrapeGraphTools", "name": "ScrapegraphAI", "category": "搜索", "description": "AI 驱动的网页结构化抓取"},
    "linkup":       {"module_path": "agno.tools.linkup", "class_name": "LinkupTools", "name": "Linkup 搜索", "category": "搜索", "description": "Linkup 实时网络搜索"},
    "apify":        {"module_path": "agno.tools.apify", "class_name": "ApifyTools", "name": "Apify 爬虫", "category": "搜索", "description": "Apify 平台网页爬取"},
    # ── 知识与数据库 ──────────────────────────────────────────────────────────
    "wikipedia":    {"module_path": "agno.tools.wikipedia", "class_name": "WikipediaTools", "name": "Wikipedia", "category": "知识", "description": "查询 Wikipedia 百科"},
    "arxiv":        {"module_path": "agno.tools.arxiv", "class_name": "ArxivTools", "name": "Arxiv 论文", "category": "知识", "description": "搜索和读取 arXiv 学术论文"},
    "pubmed":       {"module_path": "agno.tools.pubmed", "class_name": "PubmedTools", "name": "PubMed 医学", "category": "知识", "description": "PubMed 医学文献搜索"},
    "hackernews":   {"module_path": "agno.tools.hackernews", "class_name": "HackerNewsTools", "name": "HackerNews", "category": "知识", "description": "HackerNews 热门文章"},
    "newspaper4k":  {"module_path": "agno.tools.newspaper4k", "class_name": "Newspaper4kTools", "name": "Newspaper4k", "category": "知识", "description": "读取新闻文章"},
    "knowledge":    {"module_path": "agno.tools.knowledge", "class_name": "KnowledgeTools", "name": "知识库工具", "category": "知识", "description": "Agno 知识库搜索/更新"},
    "sql":          {"module_path": "agno.tools.sql", "class_name": "SQLTools", "name": "SQL 工具", "category": "数据库", "description": "执行 SQL 查询"},
    "postgres":     {"module_path": "agno.tools.postgres", "class_name": "PostgresTools", "name": "PostgreSQL 工具", "category": "数据库", "description": "PostgreSQL 数据库操作"},
    "duckdb":       {"module_path": "agno.tools.duckdb", "class_name": "DuckDbTools", "name": "DuckDB 工具", "category": "数据库", "description": "DuckDB 内存分析数据库"},
    "pandas":       {"module_path": "agno.tools.pandas", "class_name": "PandasTools", "name": "Pandas 工具", "category": "数据", "description": "Pandas 数据分析操作"},
    "csv_tools":    {"module_path": "agno.tools.csv_toolkit", "class_name": "CsvTools", "name": "CSV 工具", "category": "数据", "description": "读写 CSV 文件"},
    "bigquery":     {"module_path": "agno.tools.google_bigquery", "class_name": "BigQueryTools", "name": "Google BigQuery", "category": "数据库", "description": "Google BigQuery 数据仓库"},
    "redshift":     {"module_path": "agno.tools.redshift", "class_name": "RedshiftTools", "name": "Redshift", "category": "数据库", "description": "Amazon Redshift 数据仓库"},
    "neo4j":        {"module_path": "agno.tools.neo4j", "class_name": "Neo4jTools", "name": "Neo4j 图数据库", "category": "数据库", "description": "Neo4j 图数据库查询"},
    # ── 文件与本地系统 ────────────────────────────────────────────────────────
    "file":         {"module_path": "agno.tools.file", "class_name": "FileTools", "name": "文件工具", "category": "文件", "description": "读写本地文件"},
    "local_fs":     {"module_path": "agno.tools.local_file_system", "class_name": "LocalFileSystemTools", "name": "本地文件系统", "category": "文件", "description": "本地文件系统操作"},
    "shell":        {"module_path": "agno.tools.shell", "class_name": "ShellTools", "name": "Shell 工具", "category": "系统", "description": "执行 Shell 命令"},
    "python":       {"module_path": "agno.tools.python", "class_name": "PythonTools", "name": "Python 执行", "category": "系统", "description": "执行 Python 代码"},
    "docker":       {"module_path": "agno.tools.docker", "class_name": "DockerTools", "name": "Docker 工具", "category": "系统", "description": "Docker 容器管理"},
    "file_gen":     {"module_path": "agno.tools.file_generation", "class_name": "FileGenerationTools", "name": "文件生成工具", "category": "文件", "description": "生成文件内容"},
    "docling":      {"module_path": "agno.tools.docling", "class_name": "DoclingTools", "name": "Docling 文档解析", "category": "文件", "description": "Docling 文档结构化解析"},
    # ── 金融与数据分析 ────────────────────────────────────────────────────────
    "yfinance":     {"module_path": "agno.tools.yfinance", "class_name": "YFinanceTools", "name": "YFinance 金融", "category": "金融", "description": "Yahoo Finance 股票数据", "param_map": {"stock_price": "enable_stock_price", "stock_fundamentals": "enable_stock_fundamentals", "income_statements": "enable_income_statements", "key_financial_ratios": "enable_key_financial_ratios", "analyst_recommendations": "enable_analyst_recommendations", "company_news": "enable_company_news", "technical_indicators": "enable_technical_indicators", "historical_prices": "enable_historical_prices", "company_info": "enable_company_info"}},
    "openbb":       {"module_path": "agno.tools.openbb", "class_name": "OpenBBTools", "name": "OpenBB 金融", "category": "金融", "description": "OpenBB 金融数据分析"},
    "financial_ds": {"module_path": "agno.tools.financial_datasets", "class_name": "FinancialDatasetsTools", "name": "Financial Datasets", "category": "金融", "description": "金融数据集 API"},
    "visualization": {"module_path": "agno.tools.visualization", "class_name": "VisualizationTools", "name": "可视化工具", "category": "数据", "description": "数据可视化图表生成"},
    # ── 通讯与协作 ────────────────────────────────────────────────────────────
    "email":        {"module_path": "agno.tools.email", "class_name": "EmailTools", "name": "邮件工具", "category": "通讯", "description": "发送 SMTP 邮件"},
    "gmail":        {"module_path": "agno.tools.gmail", "class_name": "GmailTools", "name": "Gmail", "category": "通讯", "description": "Gmail 邮件操作"},
    "slack":        {"module_path": "agno.tools.slack", "class_name": "SlackTools", "name": "Slack", "category": "通讯", "description": "Slack 消息发送"},
    "telegram":     {"module_path": "agno.tools.telegram", "class_name": "TelegramTools", "name": "Telegram", "category": "通讯", "description": "Telegram Bot 消息"},
    "discord":      {"module_path": "agno.tools.discord", "class_name": "DiscordTools", "name": "Discord", "category": "通讯", "description": "Discord 消息"},
    "twilio":       {"module_path": "agno.tools.twilio", "class_name": "TwilioTools", "name": "Twilio", "category": "通讯", "description": "Twilio 短信/语音"},
    "resend":       {"module_path": "agno.tools.resend", "class_name": "ResendTools", "name": "Resend 邮件", "category": "通讯", "description": "Resend 邮件 API"},
    "webex":        {"module_path": "agno.tools.webex", "class_name": "WebexTools", "name": "Webex", "category": "通讯", "description": "Cisco Webex 协作"},
    "zoom":         {"module_path": "agno.tools.zoom", "class_name": "ZoomTools", "name": "Zoom", "category": "通讯", "description": "Zoom 会议管理"},
    "calcom":       {"module_path": "agno.tools.calcom", "class_name": "CalComTools", "name": "Cal.com 日历", "category": "通讯", "description": "Cal.com 日程预约"},
    # ── 项目与任务管理 ────────────────────────────────────────────────────────
    "github":       {"module_path": "agno.tools.github", "class_name": "GithubTools", "name": "GitHub", "category": "开发", "description": "GitHub 仓库操作"},
    "gitlab":       {"module_path": "agno.tools.gitlab", "class_name": "GitlabTools", "name": "GitLab", "category": "开发", "description": "GitLab 操作"},
    "bitbucket":    {"module_path": "agno.tools.bitbucket", "class_name": "BitbucketTools", "name": "Bitbucket", "category": "开发", "description": "Bitbucket 代码仓库"},
    "coding":       {"module_path": "agno.tools.coding", "class_name": "CodingTools", "name": "Coding 工具", "category": "开发", "description": "代码生成/执行辅助"},
    "e2b":          {"module_path": "agno.tools.e2b", "class_name": "E2BTools", "name": "E2B 代码执行", "category": "开发", "description": "E2B 安全代码执行沙箱"},
    "daytona":      {"module_path": "agno.tools.daytona", "class_name": "DaytonaTools", "name": "Daytona", "category": "开发", "description": "Daytona 开发环境管理"},
    "jira":         {"module_path": "agno.tools.jira", "class_name": "JiraTools", "name": "Jira", "category": "项目管理", "description": "Jira 任务管理"},
    "linear":       {"module_path": "agno.tools.linear", "class_name": "LinearTools", "name": "Linear", "category": "项目管理", "description": "Linear 任务管理"},
    "clickup":      {"module_path": "agno.tools.clickup", "class_name": "ClickUpTools", "name": "ClickUp", "category": "项目管理", "description": "ClickUp 项目管理"},
    "trello":       {"module_path": "agno.tools.trello", "class_name": "TrelloTools", "name": "Trello", "category": "项目管理", "description": "Trello 看板"},
    "notion":       {"module_path": "agno.tools.notion", "class_name": "NotionTools", "name": "Notion", "category": "项目管理", "description": "Notion 笔记/知识库"},
    "todoist":      {"module_path": "agno.tools.todoist", "class_name": "TodoistTools", "name": "Todoist", "category": "项目管理", "description": "Todoist 任务清单"},
    "confluence":   {"module_path": "agno.tools.confluence", "class_name": "ConfluenceTools", "name": "Confluence", "category": "项目管理", "description": "Confluence 文档协作"},
    "airflow":      {"module_path": "agno.tools.airflow", "class_name": "AirflowTools", "name": "Airflow", "category": "数据", "description": "Apache Airflow DAG 管理"},
    # ── Google 生态 ───────────────────────────────────────────────────────────
    "google_calendar": {"module_path": "agno.tools.googlecalendar", "class_name": "GoogleCalendarTools", "name": "Google 日历", "category": "Google", "description": "Google Calendar 日历管理"},
    "google_drive":    {"module_path": "agno.tools.google_drive", "class_name": "GoogleDriveTools", "name": "Google Drive", "category": "Google", "description": "Google Drive 文件管理"},
    "google_maps":     {"module_path": "agno.tools.google_maps", "class_name": "GoogleMapsTools", "name": "Google Maps", "category": "Google", "description": "Google Maps 地图服务"},
    "google_sheets":   {"module_path": "agno.tools.googlesheets", "class_name": "GoogleSheetsTools", "name": "Google Sheets", "category": "Google", "description": "Google Sheets 表格操作"},
    # ── AI 与图像生成 ─────────────────────────────────────────────────────────
    "dalle":        {"module_path": "agno.tools.dalle", "class_name": "DalleTools", "name": "DALL-E 图像", "category": "AI生成", "description": "OpenAI DALL-E 图像生成"},
    "openai_tools": {"module_path": "agno.tools.openai", "class_name": "OpenAITools", "name": "OpenAI 工具", "category": "AI生成", "description": "OpenAI 通用工具"},
    "replicate":    {"module_path": "agno.tools.replicate", "class_name": "ReplicateTools", "name": "Replicate", "category": "AI生成", "description": "Replicate AI 模型运行"},
    "fal":          {"module_path": "agno.tools.fal", "class_name": "FalTools", "name": "Fal AI", "category": "AI生成", "description": "Fal.ai 图像/视频生成"},
    "eleven_labs":  {"module_path": "agno.tools.eleven_labs", "class_name": "ElevenLabsTools", "name": "Eleven Labs 语音", "category": "AI生成", "description": "ElevenLabs 文字转语音"},
    "opencv":       {"module_path": "agno.tools.opencv", "class_name": "OpenCVTools", "name": "OpenCV 图像", "category": "AI生成", "description": "OpenCV 图像处理"},
    # ── 推理与控制 ────────────────────────────────────────────────────────────
    "reasoning":    {"module_path": "agno.tools.reasoning", "class_name": "ReasoningTools", "name": "推理工具", "category": "推理", "description": "CoT 推理辅助工具"},
    "calculator":   {"module_path": "agno.tools.calculator", "class_name": "CalculatorTools", "name": "计算器", "category": "工具", "description": "数学计算器"},
    "scheduler":    {"module_path": "agno.tools.scheduler", "class_name": "SchedulerTools", "name": "调度工具", "category": "工具", "description": "定时任务调度"},
    "sleep":        {"module_path": "agno.tools.sleep", "class_name": "SleepTools", "name": "Sleep 工具", "category": "工具", "description": "等待/延迟执行"},
    "user_control": {"module_path": "agno.tools.user_control_flow", "class_name": "UserControlFlowTools", "name": "用户控制流", "category": "工具", "description": "用户交互控制流"},
    "user_feedback": {"module_path": "agno.tools.user_feedback", "class_name": "UserFeedbackTools", "name": "用户反馈", "category": "工具", "description": "收集用户反馈"},
    "memory":       {"module_path": "agno.tools.memory", "class_name": "MemoryTools", "name": "记忆工具", "category": "工具", "description": "Agent 记忆管理"},
    "zep":          {"module_path": "agno.tools.zep", "class_name": "ZepTools", "name": "Zep 记忆", "category": "工具", "description": "Zep 长期记忆管理"},
    "custom_api":   {"module_path": "agno.tools.api", "class_name": "CustomApiTools", "name": "自定义 API", "category": "工具", "description": "调用自定义 REST API"},
    "openweather":  {"module_path": "agno.tools.openweather", "class_name": "OpenWeatherTools", "name": "OpenWeather", "category": "工具", "description": "OpenWeatherMap 天气查询"},
    "brandfetch":   {"module_path": "agno.tools.brandfetch", "class_name": "BrandfetchTools", "name": "Brandfetch", "category": "工具", "description": "品牌信息查询"},
    # ── 其他 ──────────────────────────────────────────────────────────────────
    "youtube_tools": {"module_path": "agno.tools.youtube", "class_name": "YouTubeTools", "name": "YouTube", "category": "媒体", "description": "YouTube 视频信息获取"},
    "reddit":       {"module_path": "agno.tools.reddit", "class_name": "RedditTools", "name": "Reddit", "category": "社交", "description": "Reddit 内容获取"},
    "x_twitter":    {"module_path": "agno.tools.x", "class_name": "XTools", "name": "X (Twitter)", "category": "社交", "description": "X (Twitter) 内容操作"},
    "shopify":      {"module_path": "agno.tools.shopify", "class_name": "ShopifyTools", "name": "Shopify", "category": "电商", "description": "Shopify 电商操作"},
    "aws_lambda":   {"module_path": "agno.tools.aws_lambda", "class_name": "AWSLambdaTools", "name": "AWS Lambda", "category": "云服务", "description": "调用 AWS Lambda 函数"},
    "zendesk":      {"module_path": "agno.tools.zendesk", "class_name": "ZendeskTools", "name": "Zendesk", "category": "客服", "description": "Zendesk 工单管理"},
    "spotify":      {"module_path": "agno.tools.spotify", "class_name": "SpotifyTools", "name": "Spotify", "category": "媒体", "description": "Spotify 音乐搜索/控制"},
    "giphy":        {"module_path": "agno.tools.giphy", "class_name": "GiphyTools", "name": "Google Giphy", "category": "媒体", "description": "Giphy GIF 搜索"},
    # ── 新增工具 ──────────────────────────────────────────────────────────────
    "agentql":      {"module_path": "agno.tools.agentql", "class_name": "AgentQLTools", "name": "AgentQL 抓取", "category": "搜索", "description": "AgentQL 结构化网页抓取"},
    "aws_ses":      {"module_path": "agno.tools.aws_ses", "class_name": "AWSSESTool", "name": "AWS SES 邮件", "category": "通讯", "description": "AWS SES 邮件发送"},
    "brightdata":   {"module_path": "agno.tools.brightdata", "class_name": "BrightDataTools", "name": "Bright Data", "category": "搜索", "description": "Bright Data 网页抓取与代理"},
    "browserbase":  {"module_path": "agno.tools.browserbase", "class_name": "BrowserbaseTools", "name": "Browserbase", "category": "搜索", "description": "Browserbase 云端浏览器自动化"},
    "cartesia":     {"module_path": "agno.tools.cartesia", "class_name": "CartesiaTools", "name": "Cartesia 语音", "category": "AI生成", "description": "Cartesia 文字转语音"},
    "desi_vocal":   {"module_path": "agno.tools.desi_vocal", "class_name": "DesiVocalTools", "name": "DesiVocal 语音", "category": "AI生成", "description": "DesiVocal 印度语文字转语音"},
    "evm":          {"module_path": "agno.tools.evm", "class_name": "EvmTools", "name": "EVM 区块链", "category": "工具", "description": "EVM 兼容区块链交互"},
    "llms_txt":     {"module_path": "agno.tools.llms_txt", "class_name": "LLMsTxtTools", "name": "LLMs.txt", "category": "知识", "description": "LLMs.txt 知识加载工具"},
    "lumalab":      {"module_path": "agno.tools.lumalab", "class_name": "LumaLabTools", "name": "Luma Lab 视频", "category": "AI生成", "description": "Luma Lab AI 视频生成"},
    "mem0":         {"module_path": "agno.tools.mem0", "class_name": "Mem0Tools", "name": "Mem0 记忆", "category": "工具", "description": "Mem0 长期记忆管理"},
    "mlx_transcribe": {"module_path": "agno.tools.mlx_transcribe", "class_name": "MLXTranscribeTools", "name": "MLX 转录", "category": "AI生成", "description": "MLX 本地音频转文字"},
    "models_labs":  {"module_path": "agno.tools.models_labs", "class_name": "ModelsLabTools", "name": "ModelsLab", "category": "AI生成", "description": "ModelsLab AI 图像/音频/视频生成"},
    "moviepy_video": {"module_path": "agno.tools.moviepy_video", "class_name": "MoviePyVideoTools", "name": "MoviePy 视频", "category": "媒体", "description": "MoviePy 视频编辑处理"},
    "nano_banana":  {"module_path": "agno.tools.nano_banana", "class_name": "NanoBananaTools", "name": "NanoBanana 图像", "category": "AI生成", "description": "NanoBanana Gemini 图像生成"},
    "newspaper":    {"module_path": "agno.tools.newspaper", "class_name": "NewspaperTools", "name": "Newspaper 新闻", "category": "知识", "description": "Newspaper 新闻文章提取"},
    "oxylabs":      {"module_path": "agno.tools.oxylabs", "class_name": "OxylabsTools", "name": "Oxylabs 抓取", "category": "搜索", "description": "Oxylabs 网页抓取与搜索"},
    "salesforce":   {"module_path": "agno.tools.salesforce", "class_name": "SalesforceTools", "name": "Salesforce", "category": "客服", "description": "Salesforce CRM 数据操作"},
    "seltz":        {"module_path": "agno.tools.seltz", "class_name": "SeltzTools", "name": "Seltz 搜索", "category": "搜索", "description": "Seltz AI 知识搜索"},
    "unsplash":     {"module_path": "agno.tools.unsplash", "class_name": "UnsplashTools", "name": "Unsplash 图片", "category": "媒体", "description": "Unsplash 免费高清图片搜索"},
    "valyu":        {"module_path": "agno.tools.valyu", "class_name": "ValyuTools", "name": "Valyu 搜索", "category": "搜索", "description": "Valyu 数据搜索"},
    "websearch":    {"module_path": "agno.tools.websearch", "class_name": "WebSearchTools", "name": "WebSearch 搜索", "category": "搜索", "description": "通用网页搜索工具"},
    "webtools":     {"module_path": "agno.tools.webtools", "class_name": "WebTools", "name": "Web 工具", "category": "搜索", "description": "URL 展开/域名解析等 Web 工具"},
    "whatsapp":     {"module_path": "agno.tools.whatsapp", "class_name": "WhatsAppTools", "name": "WhatsApp", "category": "通讯", "description": "WhatsApp Business 消息发送"},
}
